# Generated by Django 4.2 on 2024-07-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Fuego', 'Fuego'), ('Planta', 'Planta'), ('Agua', 'Agua'), ('Tierra', 'Tierra'), ('EElectrico', 'Eléctrico')], max_length=30),
        ),
    ]
