# Generated by Django 4.2 on 2024-07-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Fuego', 'Fuego'), ('Tierra', 'Tierra'), ('Eléctrico', 'Eléctrico'), ('Planta', 'Planta'), ('Agua', 'Agua')], max_length=30),
        ),
    ]
